nmixer: always use "%s"-style format for printf()-style functions
`ncuses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in palce of format
string when built with CFLAGS=-Werror=format-security:

    nmixer.cc:219:26: error: format not a string literal and no format arguments [-Werror=format-security]
      219 |                 mvwprintw(mixwin, my_y - 1, my_x, (char*)source);
          |                 ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Let's wrap all the missing places with "%s" format.